# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_Dialog(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(724, 335)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(724, 335))
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.46729, y2:1, stop:0 rgba(115, 125, 254, 255), stop:1 rgba(255, 202, 201, 255))")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.46729, y2:1, stop:0 rgba(115, 125, 254, 255), stop:1 rgba(255, 202, 201, 255))")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setStyleSheet("background-color: rgba(0,0,0,10);\n"
"border: 2px solid rgba(143, 184, 237, 1);\n"
"border-radius: 7px;\n"
"\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 24, 105);")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_3.addWidget(self.label_8)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Tsk1 = QtWidgets.QPushButton(self.frame_2)
        self.Tsk1.setMinimumSize(QtCore.QSize(0, 74))
        self.Tsk1.setMaximumSize(QtCore.QSize(128, 74))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Tsk1.setFont(font)
        self.Tsk1.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.Tsk1.setStyleSheet("color: rgb(0, 24, 105);\n"
"background-color: rgb(255, 255, 255);")
        self.Tsk1.setObjectName("Tsk1")
        self.horizontalLayout.addWidget(self.Tsk1)
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 24, 105);")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout.addWidget(self.label_9)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Tsk2 = QtWidgets.QPushButton(self.frame_2)
        self.Tsk2.setMinimumSize(QtCore.QSize(128, 74))
        self.Tsk2.setMaximumSize(QtCore.QSize(150, 97))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Tsk2.setFont(font)
        self.Tsk2.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.Tsk2.setStyleSheet("color: rgb(0, 24, 105);\n"
"background-color: rgb(255, 255, 255);")
        self.Tsk2.setObjectName("Tsk2")
        self.horizontalLayout_2.addWidget(self.Tsk2)
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 24, 105);")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_2.addWidget(self.label_10)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Tsk3 = QtWidgets.QPushButton(self.frame_2)
        self.Tsk3.setMinimumSize(QtCore.QSize(0, 74))
        self.Tsk3.setMaximumSize(QtCore.QSize(128, 74))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Tsk3.setFont(font)
        self.Tsk3.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.Tsk3.setStyleSheet("color: rgb(0, 24, 105);\n"
"background-color: rgb(255, 255, 255);")
        self.Tsk3.setObjectName("Tsk3")
        self.horizontalLayout_3.addWidget(self.Tsk3)
        self.label_11 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 24, 105);")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_3.addWidget(self.label_11)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_8.setText(_translate("MainWindow", "Выберите задание"))
        self.Tsk1.setText(_translate("MainWindow", "Задание 1"))
        self.label_9.setText(_translate("MainWindow", "Нахождение вероятности отказа заданной схемы, \n"
"используя алгебраические операции над событиями\n"
" и теоремы сложения и умножения вероятностей"))
        self.Tsk2.setText(_translate("MainWindow", "Задание 2"))
        self.label_10.setText(_translate("MainWindow", "Выбор подходящих промежуточных событий\n"
" и использование операций над событиями\n"
" и теорем сложения и умножения вероятностей для отыскания\n"
"вероятностей заданных сложных событий."))
        self.Tsk3.setText(_translate("MainWindow", "Задание 3"))
        self.label_11.setText(_translate("MainWindow", "Формулы полной вероятности и Байеса"))

