from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_Tsk2(object):
    def setupUi(self, MainWindow_Tsk2):
        MainWindow_Tsk2.setObjectName("MainWindow_Tsk2")
        MainWindow_Tsk2.resize(759, 867)
        MainWindow_Tsk2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        MainWindow_Tsk2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.46729, y2:1, stop:0 rgba(115, 125, 254, 255), stop:1 rgba(255, 202, 201, 255))\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow_Tsk2)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setStyleSheet("background-color: rgba(0,0,0,10);\n"
"border: 2px solid rgba(143, 184, 237, 1);\n"
"border-radius: 7px;\n"
"\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 24, 105);")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_3.addWidget(self.label_8)
        self.frame = QtWidgets.QFrame(self.frame_2)
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 2px solid rgba(143, 184, 237, 1);\n"
"border-radius: 7px;\n"
"\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setMinimumSize(QtCore.QSize(395, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(0, 24, 105);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_8.addWidget(self.label_3)
        self.p3 = QtWidgets.QDoubleSpinBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.p3.setFont(font)
        self.p3.setStyleSheet("color: rgb(0, 24, 105);")
        self.p3.setAlignment(QtCore.Qt.AlignCenter)
        self.p3.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.p3.setDecimals(4)
        self.p3.setMaximum(1.0)
        self.p3.setObjectName("p3")
        self.horizontalLayout_8.addWidget(self.p3)
        self.gridLayout.addLayout(self.horizontalLayout_8, 2, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setMinimumSize(QtCore.QSize(395, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(0, 24, 105);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_9.addWidget(self.label_4)
        self.p4 = QtWidgets.QDoubleSpinBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.p4.setFont(font)
        self.p4.setStyleSheet("color: rgb(0, 24, 105);")
        self.p4.setAlignment(QtCore.Qt.AlignCenter)
        self.p4.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.p4.setDecimals(4)
        self.p4.setMaximum(1.0)
        self.p4.setObjectName("p4")
        self.horizontalLayout_9.addWidget(self.p4)
        self.gridLayout.addLayout(self.horizontalLayout_9, 3, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setMinimumSize(QtCore.QSize(395, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(0, 24, 105);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_7.addWidget(self.label_2)
        self.p2 = QtWidgets.QDoubleSpinBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.p2.setFont(font)
        self.p2.setStyleSheet("color: rgb(0, 24, 105);")
        self.p2.setAlignment(QtCore.Qt.AlignCenter)
        self.p2.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.p2.setDecimals(4)
        self.p2.setMaximum(1.0)
        self.p2.setObjectName("p2")
        self.horizontalLayout_7.addWidget(self.p2)
        self.gridLayout.addLayout(self.horizontalLayout_7, 1, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setMinimumSize(QtCore.QSize(395, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(0, 24, 105);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.p1 = QtWidgets.QDoubleSpinBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.p1.setFont(font)
        self.p1.setStyleSheet("color: rgb(0, 24, 105);")
        self.p1.setAlignment(QtCore.Qt.AlignCenter)
        self.p1.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.p1.setDecimals(4)
        self.p1.setMaximum(1.0)
        self.p1.setObjectName("p1")
        self.horizontalLayout_6.addWidget(self.p1)
        self.gridLayout.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.frame)
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 2px solid rgba(143, 184, 237, 1);\n"
"border-radius: 7px;\n"
"\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_9 = QtWidgets.QLabel(self.frame_3)
        self.label_9.setMinimumSize(QtCore.QSize(395, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 24, 105);")
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout.addWidget(self.label_9)
        self.a_res = QtWidgets.QLineEdit(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.a_res.setFont(font)
        self.a_res.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.a_res.setStyleSheet("color: rgb(0, 0, 0);\n"
"color: rgb(0, 24, 105);\n"
"background-color: white;")
        self.a_res.setInputMask("")
        self.a_res.setText("")
        self.a_res.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.a_res.setAlignment(QtCore.Qt.AlignCenter)
        self.a_res.setDragEnabled(False)
        self.a_res.setReadOnly(True)
        self.a_res.setPlaceholderText("")
        self.a_res.setObjectName("a_res")
        self.horizontalLayout.addWidget(self.a_res)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_13 = QtWidgets.QLabel(self.frame_3)
        self.label_13.setMinimumSize(QtCore.QSize(395, 0))
        self.label_13.setMaximumSize(QtCore.QSize(711, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 24, 105);")
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("Tsk2_1corr.png"))
        self.label_13.setScaledContents(True)
        self.label_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.verticalLayout.addWidget(self.label_13)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_10 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 24, 105);")
        self.label_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_2.addWidget(self.label_10)
        self.b_res = QtWidgets.QLineEdit(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.b_res.setFont(font)
        self.b_res.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.b_res.setStyleSheet("color: rgb(0, 0, 0);\n"
"color: rgb(0, 24, 105);\n"
"background-color: white;")
        self.b_res.setInputMask("")
        self.b_res.setText("")
        self.b_res.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.b_res.setAlignment(QtCore.Qt.AlignCenter)
        self.b_res.setDragEnabled(False)
        self.b_res.setReadOnly(True)
        self.b_res.setPlaceholderText("")
        self.b_res.setObjectName("b_res")
        self.horizontalLayout_2.addWidget(self.b_res)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.label_14 = QtWidgets.QLabel(self.frame_3)
        self.label_14.setMinimumSize(QtCore.QSize(395, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 24, 105);")
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap("Tsk2_2.png"))
        self.label_14.setScaledContents(False)
        self.label_14.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.label_14.setMinimumSize(QtCore.QSize(395, 0))
        self.label_14.setMaximumSize(QtCore.QSize(711, 16777215))
        self.verticalLayout_2.addWidget(self.label_14)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 1, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_11 = QtWidgets.QLabel(self.frame_3)
        self.label_11.setMinimumSize(QtCore.QSize(395, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 24, 105);")
        self.label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_3.addWidget(self.label_11)
        self.c_res = QtWidgets.QLineEdit(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.c_res.setFont(font)
        self.c_res.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.c_res.setStyleSheet("color: rgb(0, 0, 0);\n"
"color: rgb(0, 24, 105);\n"
"background-color: white;")
        self.c_res.setInputMask("")
        self.c_res.setText("")
        self.c_res.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.c_res.setAlignment(QtCore.Qt.AlignCenter)
        self.c_res.setDragEnabled(False)
        self.c_res.setReadOnly(True)
        self.c_res.setPlaceholderText("")
        self.c_res.setObjectName("c_res")
        self.horizontalLayout_3.addWidget(self.c_res)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.frame_3)
        self.label_15.setMinimumSize(QtCore.QSize(395, 0))
        self.label_15.setMaximumSize(QtCore.QSize(711, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 24, 105);")
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap("Tsk2_3.png"))
        self.label_15.setScaledContents(True)
        self.label_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 1, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 2, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_12 = QtWidgets.QLabel(self.frame_3)
        self.label_12.setMinimumSize(QtCore.QSize(395, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 24, 105);")
        self.label_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_4.addWidget(self.label_12)
        self.d_res = QtWidgets.QLineEdit(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.d_res.setFont(font)
        self.d_res.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.d_res.setStyleSheet("color: rgb(0, 0, 0);\n"
"color: rgb(0, 24, 105);\n"
"background-color: white;")
        self.d_res.setInputMask("")
        self.d_res.setText("")
        self.d_res.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.d_res.setAlignment(QtCore.Qt.AlignCenter)
        self.d_res.setDragEnabled(False)
        self.d_res.setReadOnly(True)
        self.d_res.setPlaceholderText("")
        self.d_res.setObjectName("d_res")
        self.horizontalLayout_4.addWidget(self.d_res)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.label_16 = QtWidgets.QLabel(self.frame_3)
        self.label_16.setMinimumSize(QtCore.QSize(395, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 24, 105);")
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap("Tsk2_4.png"))
        self.label_16.setScaledContents(False)
        self.label_16.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_4.addWidget(self.label_16)
        self.gridLayout_3.addLayout(self.verticalLayout_4, 3, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.back_2 = QtWidgets.QPushButton(self.frame_3)
        self.back_2.setMinimumSize(QtCore.QSize(395, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.back_2.setFont(font)
        self.back_2.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.back_2.setStyleSheet("color: rgb(0, 24, 105);\n"
"background-color: rgb(255, 255, 255);")
        self.back_2.setObjectName("back_2")
        self.horizontalLayout_5.addWidget(self.back_2)
        self.result_2 = QtWidgets.QPushButton(self.frame_3)
        self.result_2.setMinimumSize(QtCore.QSize(81, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.result_2.setFont(font)
        self.result_2.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.result_2.setStyleSheet("color: rgb(0, 24, 105);\n"
"background-color: rgb(255, 255, 255);")
        self.result_2.setObjectName("result_2")
        self.horizontalLayout_5.addWidget(self.result_2)
        self.gridLayout_3.addLayout(self.horizontalLayout_5, 4, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.frame_3)
        self.gridLayout_5.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_2, 0, 0, 1, 1)
        MainWindow_Tsk2.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow_Tsk2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_Tsk2)

    def retranslateUi(self, MainWindow_Tsk2):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_Tsk2.setWindowTitle(_translate("MainWindow_Tsk2", "MainWindow"))
        self.label_8.setText(_translate("MainWindow_Tsk2", "Рабочий обслуживает 4 станка, работающих независимо друг от друга. Ве-\n"
"роятность того, что за смену i-ый станок потребует наладки, равна pi. Найти веро-\n"
"ятность событий"))
        self.label_3.setText(_translate("MainWindow_Tsk2", "P3"))
        self.label_4.setText(_translate("MainWindow_Tsk2", "P4"))
        self.label_2.setText(_translate("MainWindow_Tsk2", "P2"))
        self.label.setText(_translate("MainWindow_Tsk2", "P1"))
        self.label_9.setText(_translate("MainWindow_Tsk2", "a) только один станок потребует наладки"))
        self.label_10.setText(_translate("MainWindow_Tsk2", "b) только третий станок потребует наладки"))
        self.label_11.setText(_translate("MainWindow_Tsk2", "c) только два станка потребуют наладки"))
        self.label_12.setText(_translate("MainWindow_Tsk2", "d) хотя бы один станок потребует наладки"))
        self.back_2.setText(_translate("MainWindow_Tsk2", "Назад"))
        self.result_2.setText(_translate("MainWindow_Tsk2", "Расчитать"))


